version: '3.0'

services:
  php-fpm:
    build:
      context: ./docker/php
    environment:
      PG_PORT: ${PG_PORT}
      PG_HOST: ${PG_HOST}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_USER: ${PG_USER}
      PG_DATABASE: ${PG_DATABASE}
    volumes:
      - ./application/backend:/symfony
    container_name: ${PROJECT_NAME}-php-fpm
    depends_on:
      - postgres
    working_dir: /symfony