controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_agreeable_puppy:
    path: /agreeable/puppy
    controller: App\Controller\AgreeablePuppyController::index